require("foundations/foundationMain")
require("foundations/foundationGlobal")
require("foundations/foundationShop")
require("foundations/foundationSettings")
require("foundations/foundationResources")